"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { motion } from "framer-motion";

import "./globals.css";
import { Header } from "@/shared/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const variants = {
    hidden: { opacity: 0, x: -200, y: 0 },
    enter: { opacity: 1, x: 0, y: 0 },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-br">
            <body className={`${inter.className} dark`}>
                <main className="flex min-h-screen dark:bg-black">
                    <div className="mx-auto max-w-7xl w-full bg-white ring-1 ring-zinc-100 dark:bg-zinc-900 dark:ring-zinc-300/20">
                        <Header />
                        <motion.div
                            variants={variants}
                            initial="hidden"
                            animate="enter"
                            transition={{ type: "linear" }}
                            className="mx-auto max-w-2xl lg:max-w-5xl sm:px-8 mt-16"
                        >
                            {children}
                        </motion.div>
                    </div>
                </main>
            </body>
        </html>
    );
}
